version: '3'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver

  service-a:
    container_name: go-service-a
    build:
      context: .
      dockerfile: service_a/Dockerfile
    environment:
      - SERVICE_B_BASE_URL=http://service-b:8081
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - otel-collector

  service-b:
    container_name: go-service-b
    build:
      context: .
      dockerfile: service_b/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - otel-collector