version: '3'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/ot-collector-config.yaml"]
    volumes:
      - ./.docker/ot-collector-config.yaml:/etc/ot-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  service-a:
    container_name: go-service-a
    build:
      context: ./service_a
    environment:
      - SERVICE_B_BASE_URL=http://service-b:8081
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - otel-collector

  service-b:
    container_name: go-service-b
    build:
      context: ./service_b
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - otel-collector